<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Analysis on Salary of Data Engineer</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="analysis_files/libs/quarto-html/quarto.js"></script>
<script src="analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="analysis_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="analysis_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#initial-data-analysis" id="toc-initial-data-analysis" class="nav-link" data-scroll-target="#initial-data-analysis">Initial Data Analysis</a>
  <ul class="collapse">
  <li><a href="#data-format-check" id="toc-data-format-check" class="nav-link" data-scroll-target="#data-format-check">Data format check</a></li>
  <li><a href="#missing-values" id="toc-missing-values" class="nav-link" data-scroll-target="#missing-values">Missing values</a></li>
  <li><a href="#filtering-data-engineer-role" id="toc-filtering-data-engineer-role" class="nav-link" data-scroll-target="#filtering-data-engineer-role">Filtering data engineer role</a></li>
  <li><a href="#re-group-company_location-variable" id="toc-re-group-company_location-variable" class="nav-link" data-scroll-target="#re-group-company_location-variable">Re-group company_location variable</a></li>
  <li><a href="#filtering-full-time-role" id="toc-filtering-full-time-role" class="nav-link" data-scroll-target="#filtering-full-time-role">Filtering full time role</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda">Exploratory Data Analysis (EDA)</a>
  <ul class="collapse">
  <li><a href="#summary-statistics" id="toc-summary-statistics" class="nav-link" data-scroll-target="#summary-statistics">Summary statistics</a>
  <ul class="collapse">
  <li><a href="#numerical-variables" id="toc-numerical-variables" class="nav-link" data-scroll-target="#numerical-variables">Numerical variables</a></li>
  <li><a href="#factor-variables" id="toc-factor-variables" class="nav-link" data-scroll-target="#factor-variables">Factor variables</a></li>
  </ul></li>
  <li><a href="#average-salary-trend" id="toc-average-salary-trend" class="nav-link" data-scroll-target="#average-salary-trend">Average Salary Trend</a></li>
  <li><a href="#average-salary-over-years-by-company-location" id="toc-average-salary-over-years-by-company-location" class="nav-link" data-scroll-target="#average-salary-over-years-by-company-location">Average Salary over Years by Company Location</a></li>
  <li><a href="#average-salary-over-years-by-experience-level" id="toc-average-salary-over-years-by-experience-level" class="nav-link" data-scroll-target="#average-salary-over-years-by-experience-level">Average Salary over Years by Experience Level</a></li>
  <li><a href="#overall-insights" id="toc-overall-insights" class="nav-link" data-scroll-target="#overall-insights">Overall Insights</a>
  <ul class="collapse">
  <li><a href="#growth-in-salaries" id="toc-growth-in-salaries" class="nav-link" data-scroll-target="#growth-in-salaries">Growth in Salaries</a></li>
  <li><a href="#location-impact" id="toc-location-impact" class="nav-link" data-scroll-target="#location-impact">Location Impact</a></li>
  <li><a href="#experience-matters" id="toc-experience-matters" class="nav-link" data-scroll-target="#experience-matters">Experience Matters</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#regression-model" id="toc-regression-model" class="nav-link" data-scroll-target="#regression-model">Regression Model</a>
  <ul class="collapse">
  <li><a href="#coefficients-and-their-interpretation" id="toc-coefficients-and-their-interpretation" class="nav-link" data-scroll-target="#coefficients-and-their-interpretation">Coefficients and Their Interpretation</a></li>
  <li><a href="#statistical-significance" id="toc-statistical-significance" class="nav-link" data-scroll-target="#statistical-significance">Statistical Significance</a></li>
  <li><a href="#model-fit" id="toc-model-fit" class="nav-link" data-scroll-target="#model-fit">Model Fit</a></li>
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways">Key Takeaways</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a>
  <ul class="collapse">
  <li><a href="#conclusion-1" id="toc-conclusion-1" class="nav-link" data-scroll-target="#conclusion-1">Conclusion</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data Analysis on Salary of Data Engineer</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>We live in a world where every piece of data significantly influences human behavior. Consequently, data scientists and data analysts are essential for interpreting and generating insightful information, enabling organizations to make data-driven decisions. However, data originates from diverse sources with varying formats and structures, complicating immediate utilization. This challenge highlights the vital role of data engineers. They design and implement systems that collect, manage, and transform raw data into formats suitable for analysis. Positioned at the initial step of the data analysis pipeline, the role of a data engineer is indispensable. This is why data engineers are in high demand across various sectors like: finance, retail and technology.</p>
<p>In this report, we will examine the salary trends for data engineers and analyze other factors influencing their income over the past four years from 2020 to 2023.</p>
<p>The data used for this analysis is <a href="https://www.kaggle.com/datasets/henryshan/2023-data-scientists-salary">2023 Data Scientists Salary</a> from <a href="https://www.kaggle.com/">Kaggle</a>, whose author is Henry Shan.</p>
</section>
<section id="initial-data-analysis" class="level1">
<h1>Initial Data Analysis</h1>
<p>Before commencing any analysis, we will review the metadata. The table below highlights every available variables in the data, as well as giving a short interpretation of each variable.</p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Explanation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>work_year</td>
<td>The year the salary was paid.</td>
</tr>
<tr class="even">
<td>experience_level</td>
<td>The experience level in the job during the year. <br> <strong>EN</strong>: Entry-level / Junior <br> <strong>MI</strong>: Mid-level / Intermediate <br> <strong>SE</strong>: Senior-level / Expert <br> <strong>EX</strong>: Executive-level / Director</td>
</tr>
<tr class="odd">
<td>employment_type</td>
<td>The type of employment for the role. <br> <strong>PT</strong>: Part-time <br> <strong>FT</strong>: Full-time <br> <strong>CT</strong>: Contract <br> <strong>FL</strong>: Freelance</td>
</tr>
<tr class="even">
<td>job_title</td>
<td>The role worked in during the year.</td>
</tr>
<tr class="odd">
<td>salary</td>
<td>The total gross salary amount paid.</td>
</tr>
<tr class="even">
<td>salary_currency</td>
<td>The currency of the salary paid as an ISO 4217 currency code.</td>
</tr>
<tr class="odd">
<td>salaryinusd</td>
<td>The salary in USD.</td>
</tr>
<tr class="even">
<td>employee_residence</td>
<td>Employee’s primary country of residence during the work year as an ISO 3166 country code.</td>
</tr>
<tr class="odd">
<td>remote_ratio</td>
<td>The overall amount of work done remotely.</td>
</tr>
<tr class="even">
<td>company_location</td>
<td>The country of the employer’s main office or contracting branch.</td>
</tr>
<tr class="odd">
<td>company_size</td>
<td>The median number of people that worked for the company during the year.</td>
</tr>
</tbody>
</table>
<section id="data-format-check" class="level2">
<h2 class="anchored" data-anchor-id="data-format-check">Data format check</h2>
<div class="cell">
<div id="tbl-dataformat" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dataformat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Data format
</figcaption>
<div aria-describedby="tbl-dataformat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<caption>Date format check</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Class</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">work_year</td>
<td style="text-align: left;">integer</td>
</tr>
<tr class="even">
<td style="text-align: left;">experience_level</td>
<td style="text-align: left;">character</td>
</tr>
<tr class="odd">
<td style="text-align: left;">employment_type</td>
<td style="text-align: left;">character</td>
</tr>
<tr class="even">
<td style="text-align: left;">job_title</td>
<td style="text-align: left;">character</td>
</tr>
<tr class="odd">
<td style="text-align: left;">salary</td>
<td style="text-align: left;">integer</td>
</tr>
<tr class="even">
<td style="text-align: left;">salary_currency</td>
<td style="text-align: left;">character</td>
</tr>
<tr class="odd">
<td style="text-align: left;">salary_in_usd</td>
<td style="text-align: left;">integer</td>
</tr>
<tr class="even">
<td style="text-align: left;">employee_residence</td>
<td style="text-align: left;">character</td>
</tr>
<tr class="odd">
<td style="text-align: left;">remote_ratio</td>
<td style="text-align: left;">integer</td>
</tr>
<tr class="even">
<td style="text-align: left;">company_location</td>
<td style="text-align: left;">character</td>
</tr>
<tr class="odd">
<td style="text-align: left;">company_size</td>
<td style="text-align: left;">character</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>At the first glance from <a href="#tbl-dataformat" class="quarto-xref">Table&nbsp;1</a>, variables such as: <code>experience_level</code>, <code>employment_type</code>. <code>job_title</code>, etc. are initially formatted as <em>character</em>, which makes the summary statistics generated for these variables meaningless.</p>
<p>To deal with this, we will convert all <em>character</em> variables into <em>factor</em> variables, then re-generate the data summary statistics.</p>
</section>
<section id="missing-values" class="level2">
<h2 class="anchored" data-anchor-id="missing-values">Missing values</h2>
<p>We then examine the data for any missing values.</p>
<div class="cell">
<div id="tbl-missingvalues" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-missingvalues-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Missing values
</figcaption>
<div aria-describedby="tbl-missingvalues-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Number of missing values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">work_year</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">experience_level</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">employment_type</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">job_title</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">salary</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">salary_currency</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">salary_in_usd</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">employee_residence</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">remote_ratio</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">company_location</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">company_size</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>As shown in <a href="#tbl-missingvalues" class="quarto-xref">Table&nbsp;2</a>, the data is complete, with no missing values present.</p>
</section>
<section id="filtering-data-engineer-role" class="level2">
<h2 class="anchored" data-anchor-id="filtering-data-engineer-role">Filtering data engineer role</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] Data Engineer           Big Data Engineer       BI Data Engineer       
[4] Software Data Engineer  Azure Data Engineer     Marketing Data Engineer
[7] Cloud Data Engineer     Lead Data Engineer      Principal Data Engineer
93 Levels: 3D Computer Vision Researcher AI Developer ... Staff Data Scientist</code></pre>
</div>
</div>
<p>There are several specific data engineer role in the data. However, for this analysis, we will only concentrate on data engineer role in general. And therefore, we will filter out <em>Data Engineer</em> value from <code>job_title</code>.</p>
</section>
<section id="re-group-company_location-variable" class="level2">
<h2 class="anchored" data-anchor-id="re-group-company_location-variable">Re-group company_location variable</h2>
<p>Moreover, we will re-group <code>company_location</code> values to <strong>US</strong> and <strong>Other</strong> for later comparison of salary between US organisations and foreign organisations.</p>
</section>
<section id="filtering-full-time-role" class="level2">
<h2 class="anchored" data-anchor-id="filtering-full-time-role">Filtering full time role</h2>
<p>Finally, we then filter from <code>employment_type</code> to <em>Full time</em> role only.</p>
</section>
</section>
<section id="exploratory-data-analysis-eda" class="level1">
<h1>Exploratory Data Analysis (EDA)</h1>
<section id="summary-statistics" class="level2">
<h2 class="anchored" data-anchor-id="summary-statistics">Summary statistics</h2>
<p>We use <code>summary()</code> to get the summary statistics of all variables. Moreover, since we have filtered to only one value for <code>job_title</code> and <code>employment_type</code>, we will not perform summary statistics for these 2 variables.</p>
<section id="numerical-variables" class="level3">
<h3 class="anchored" data-anchor-id="numerical-variables">Numerical variables</h3>
<div id="tbl-numsum" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-numsum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Summary statistics of numerical variables
</figcaption>
<div aria-describedby="tbl-numsum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code>   work_year        salary        salary_in_usd     remote_ratio   
 Min.   :2020   Min.   :  12000   Min.   : 12000   Min.   :  0.00  
 1st Qu.:2022   1st Qu.: 102100   1st Qu.:102000   1st Qu.:  0.00  
 Median :2022   Median : 138750   Median :135000   Median :  0.00  
 Mean   :2022   Mean   : 156904   Mean   :143062   Mean   : 42.33  
 3rd Qu.:2023   3rd Qu.: 177600   3rd Qu.:175000   3rd Qu.:100.00  
 Max.   :2023   Max.   :4450000   Max.   :324000   Max.   :100.00  </code></pre>
</div>
</div>
</figure>
</div>
<p>Given that the salary for the data engineer role is paid in the currency of the company’s location, we will use <code>salary_in_usd</code> for our analysis.</p>
<p>As shown in <a href="#tbl-numsum" class="quarto-xref">Table&nbsp;3</a>, the annual salaries for data engineers range from <em>12,000 USD</em> to <em>324,000 USD</em>, with a mean salary of approximately <strong>143,000 USD</strong>. This significant disparity in pay can be attributed to various factors, including the location of the role and the data engineer’s level of experience.</p>
</section>
<section id="factor-variables" class="level3">
<h3 class="anchored" data-anchor-id="factor-variables">Factor variables</h3>
<div id="tbl-facsum" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-facsum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Summary statistics of factor variables
</figcaption>
<div aria-describedby="tbl-facsum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code> experience_level salary_currency employee_residence company_size company_loc
 EN: 66           USD    :922     US     :903        L: 76        Other:131  
 EX: 51           GBP    : 54     GB     : 53        M:953        US   :906  
 MI:202           EUR    : 49     ES     : 21        S:  8                   
 SE:718           INR    :  6     CA     :  8                                
                  TRY    :  2     GR     :  7                                
                  AUD    :  1     IN     :  6                                
                  (Other):  3     (Other): 39                                </code></pre>
</div>
</div>
</figure>
</div>
<p>As we can see from <a href="#tbl-facsum" class="quarto-xref">Table&nbsp;4</a>, for both <code>company_loc</code> as well as <code>employee_residence</code>, highest frequency values are <em>US</em>. This may happen due to a few reasons:</p>
<ol type="1">
<li><p><strong>Large Tech Industry Presence</strong>: The United States is home to many of the world’s largest technology companies, such as Google, Apple, Microsoft, and Amazon. These companies often have significant demand for data engineers and other data-related roles, leading to a higher concentration of such jobs in the US.</p></li>
<li><p><strong>Higher Salaries and Better Opportunities</strong>: Salaries for tech roles, including data engineers, tend to be higher in the US compared to other countries. This attracts talent from around the world to seek employment in the US, contributing to the higher frequency of employees residing in the US.</p></li>
<li><p><strong>Headquarters Location</strong>: Many multinational tech companies have their headquarters in the US. As a result, their main offices are located there, increasing the frequency of the US as the company location.</p></li>
</ol>
<p>Moreover, most of the data engineers for this data is currently in <em>SE</em> or Senior-level role.</p>
</section>
</section>
<section id="average-salary-trend" class="level2">
<h2 class="anchored" data-anchor-id="average-salary-trend">Average Salary Trend</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-salarytrend" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-salarytrend-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analysis_files/figure-html/fig-salarytrend-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-salarytrend-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Average salary trend
</figcaption>
</figure>
</div>
</div>
</div>
<p>As we can see from <a href="#fig-salarytrend" class="quarto-xref">Figure&nbsp;1</a>, there is a consistent upward trend in the average salary for data engineers from 2020 to 2023.</p>
<p>The average salary has increased significantly each year, indicating a growing demand for data engineers and possibly an increasing recognition of the value they bring to organizations.</p>
</section>
<section id="average-salary-over-years-by-company-location" class="level2">
<h2 class="anchored" data-anchor-id="average-salary-over-years-by-company-location">Average Salary over Years by Company Location</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-salarycom" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-salarycom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analysis_files/figure-html/fig-salarycom-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-salarycom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Average salary by company location
</figcaption>
</figure>
</div>
</div>
</div>
<p>From <a href="#fig-salarycom" class="quarto-xref">Figure&nbsp;2</a>, we can see that there is a huge gap in salary of data engineers between US organisations and foreign organisations. This may reflect the higher cost of living in the US, greater demand for tech talent, or more competitive salary packages offered by US companies.</p>
<ul>
<li><p><strong>US</strong>: Salaries in the US have shown a more stable and slightly upward trend overall. However, there is a slight decrease from 2020 to 2021, followed by a significant increase from 2021 to 2022, and a continued rise into 2023.</p></li>
<li><p><strong>Other Locations</strong>: Salaries in other locations have followed a similar pattern. There is a slight increase from 2020 to 2021, a significant jump from 2021 to 2022, and a continued rise from 2022 to 2023.</p></li>
</ul>
</section>
<section id="average-salary-over-years-by-experience-level" class="level2">
<h2 class="anchored" data-anchor-id="average-salary-over-years-by-experience-level">Average Salary over Years by Experience Level</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-salaryexper" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-salaryexper-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analysis_files/figure-html/fig-salaryexper-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-salaryexper-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Average salary by experience
</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><strong>Experience Level Impact</strong>:
<ul>
<li><strong>Executive-level (EX)</strong>: Executive-level data engineers see the highest salaries, with a notable peak around 2022, indicating high rewards for top-tier experience and leadership roles.</li>
<li><strong>Senior-level (SE)</strong>: Senior-level salaries show a steady upward trend, reflecting the growing value of experienced professionals.</li>
<li><strong>Mid-level (MI)</strong>: Mid-level salaries have been relatively stable with a slight increase, indicating moderate growth in compensation for this experience tier.</li>
<li><strong>Entry-level (EN)</strong>: Entry-level salaries have seen a substantial increase from 2020 to 2022, though there is a slight decline in 2023. This could suggest a correction or stabilization in entry-level hiring and compensation.</li>
</ul></li>
</ul>
</section>
<section id="overall-insights" class="level2">
<h2 class="anchored" data-anchor-id="overall-insights">Overall Insights</h2>
<section id="growth-in-salaries" class="level3">
<h3 class="anchored" data-anchor-id="growth-in-salaries">Growth in Salaries</h3>
<p>Salaries for data engineers have been on the rise overall, with significant variations depending on both location and experience level.</p>
</section>
<section id="location-impact" class="level3">
<h3 class="anchored" data-anchor-id="location-impact">Location Impact</h3>
<p>The United States stands out as the highest-paying region for data engineers. This can be attributed to the country’s strong tech industry and higher cost of living, which drives up salary levels.</p>
</section>
<section id="experience-matters" class="level3">
<h3 class="anchored" data-anchor-id="experience-matters">Experience Matters</h3>
<p>Experience plays a crucial role in determining salary. Executive and senior-level positions earn the highest pay, reflecting their expertise and leadership responsibilities. Entry-level positions, while showing positive growth, exhibit some fluctuations.</p>
<p>These trends underscore the dynamic and evolving landscape of the data engineering field. There is growing recognition of the value data professionals bring, coupled with a competitive job market that continues to push salaries upward.</p>
</section>
</section>
</section>
<section id="regression-model" class="level1">
<h1>Regression Model</h1>
<p>For better understanding on how experience level and company location affects the salary of data engineer, we fit a linear model for <code>salary_in_usd</code> against <code>company_loc</code> and <code>experience_level</code>. We also include <code>work_year</code> in the regression as explanatory variable to encounter for the trend pattern.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tar_read</span>(summary_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary_in_usd ~ work_year + experience_level + company_loc, 
    data = de_data_clean)

Residuals:
    Min      1Q  Median      3Q     Max 
-128935  -32033   -3935   26065  161065 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        -10086485    5013887  -2.012   0.0445 *  
work_year               5012       2480   2.021   0.0435 *  
experience_levelEX    102667       9042  11.354  &lt; 2e-16 ***
experience_levelMI     22005       6822   3.225   0.0013 ** 
experience_levelSE     48895       6252   7.820  1.3e-14 ***
company_locUS          57474       5055  11.369  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 47950 on 1031 degrees of freedom
Multiple R-squared:  0.317, Adjusted R-squared:  0.3137 
F-statistic: 95.71 on 5 and 1031 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<section id="coefficients-and-their-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="coefficients-and-their-interpretation">Coefficients and Their Interpretation</h3>
<ul>
<li><p><strong>Intercept</strong>: The negative intercept (-10,086,485) is not directly interpretable in a meaningful way.</p></li>
<li><p><strong>Work Year</strong>: The positive coefficient for <code>work_year</code> (5012) indicates that for each additional year, the salary increases by approximately $5,012, holding other factors constant. This suggests a general upward trend in salaries over time.</p></li>
<li><p><strong>Experience Level</strong>:</p>
<ul>
<li><strong>Executive Level (EX)</strong>: With a coefficient of 102,667, executive-level data engineers earn significantly higher salaries compared to the baseline (entry-level), all else being equal.</li>
<li><strong>Senior Level (SE)</strong>: The coefficient of 48,895 shows that senior-level engineers earn about $48,895 more than entry-level engineers.</li>
<li><strong>Mid-Level (MI)</strong>: The coefficient of 22,005 indicates that mid-level data engineers earn about $22,005 more than entry-level engineers.</li>
</ul></li>
<li><p><strong>Company Location</strong></p>
<ul>
<li><strong>US Location</strong>: The coefficient of 57,474 for <code>company_locUS</code> means that data engineers working in the US earn about $57,474 more than their counterparts in other locations.</li>
</ul></li>
</ul>
</section>
<section id="statistical-significance" class="level3">
<h3 class="anchored" data-anchor-id="statistical-significance">Statistical Significance</h3>
<ul>
<li>The p-values for <code>work_year</code>, <code>experience_level</code> (EX, MI, SE), and <code>company_locUS</code> are all less than 0.05, indicating that these predictors are statistically significant.</li>
</ul>
</section>
<section id="model-fit" class="level3">
<h3 class="anchored" data-anchor-id="model-fit">Model Fit</h3>
<ul>
<li><strong>R-squared</strong>: The model explains about 31.7% of the variance in salaries (<code>R-squared = 0.317</code>), which is reasonable for a model with a few predictors but suggests there are other factors influencing salary that are not captured by this model.</li>
</ul>
</section>
<section id="key-takeaways" class="level3">
<h3 class="anchored" data-anchor-id="key-takeaways">Key Takeaways</h3>
<ol type="1">
<li><strong>Yearly Salary Increase</strong>: There is a steady increase in data engineer salaries over the years, with an average annual increase of $5,012.</li>
<li><strong>Experience Level Impact</strong>: Higher experience levels (especially executive and senior levels) significantly boost salaries, reflecting the premium placed on experience and expertise in the field.</li>
<li><strong>Geographical Impact</strong>: Working in the US significantly enhances salary prospects, likely due to the strong tech industry and higher cost of living.</li>
</ol>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<section id="conclusion-1" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-1">Conclusion</h3>
<p>In conclusion, the analysis reveals a significant upward trend in data engineer salaries over the past few years, driven by factors such as experience level and geographical location. Executive and senior-level positions command the highest salaries, highlighting the value placed on experience and expertise. Additionally, data engineers based in the United States enjoy higher salaries compared to those in other locations, reflecting the strong demand and competitive compensation in the US tech industry.</p>
<p>These findings underscore the dynamic nature of the data engineering field and the growing recognition of the critical role data professionals play in modern organizations. As the demand for skilled data engineers continues to rise, understanding the factors that influence salary trends can provide valuable insights for both employers and job seekers, guiding strategic decisions in recruitment, career planning, and compensation management.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>